[tool.poetry]
name = "demographic-data-analyser"
version = "0.1.0"
description = ""
authors = ["Dtzz81 <denise.turkova@madetech.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
